### ISSUE TITLE
Alterações página inicial

### ISSUE THREAD

**Issue by desenvolvedorcmo** [desenvolvedorcmo/reserva#4]
Traduzir a página inicial:

- Menu Agende colocar Agendamentos
  > http://localhost/crbs-2.4.1/index.php/ -> School Details -> Cadastro Órgão
      
   -> http://localhost/crbs-2.4.1/index.php/school 
    Título: School Details -> Cadastro do Órgão
    School Information -> Infomações do Órgão
    School Name -> Nome
    Website address -> Website

    School Logo: Logo
    Current Logo -> Logo atual
    File Upload -> Upload
    Delete Logo? -> Remover Logo  

-------------------------------------------------------

Título: The School Day -> Períodos de Agendamento

Traduzir os campos, botões e labels.

**Comment by eaeDanilo** [comment]
OK
